// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicP_qEEv7WmJxhPObUf_e8gs4uIp8uYQ',
    appId: '1:242518865307:web:62dde16f38084b5f151d3e',
    messagingSenderId: '242518865307',
    projectId: 'pneuma-firebase',
    authDomain: 'pneuma-firebase.firebaseapp.com',
    storageBucket: 'pneuma-firebase.firebasestorage.app',
    measurementId: 'G-ZGP35756PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0rkD6mm0qbRf8K63sFrhmBqtIC1GeSA',
    appId: '1:242518865307:android:610d5f35024a5d04151d3e',
    messagingSenderId: '242518865307',
    projectId: 'pneuma-firebase',
    storageBucket: 'pneuma-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uG7vWVPlvwpDCoY3OSj-d1Z6bU2WJkU',
    appId: '1:242518865307:ios:8ee74c87680b1332151d3e',
    messagingSenderId: '242518865307',
    projectId: 'pneuma-firebase',
    storageBucket: 'pneuma-firebase.firebasestorage.app',
    iosBundleId: 'com.pneumage.pneumageApp',
  );
}
